/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Claudivan Moreira
 * Created: 09/04/2017
 */

create table cards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    card_name VARCHAR(100),
    flag_of_card VARCHAR(100),
    card_limit VARCHAR (10),
    invoice_due_date VARCHAR (10),
    invoice_close_date VARCHAR (10)
);

create table categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    category_name VARCHAR(100),
    category_type VARCHAR(100)
);

create table dreams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    dream_name VARCHAR(100),
    amount_value VARCHAR(100),
    saved_value VARCHAR(100)
);

create table card_expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    expense_value DOUBLE,
    expense_date DATE,
    description VARCHAR(100),
    fixed_expense BOOLEAN,
    number_of_payment_installments INTEGER,
    send_email_reminder BOOLEAN,
    card_id INTEGER,
    category_id INTEGER,
    FOREIGN KEY (card_id) references cards(id),
    FOREIGN KEY (category_id) references categories(id)
);

create table general_expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    expense_value DOUBLE,
    expense_date DATE,
    description VARCHAR(100),
    fixed_expense BOOLEAN,
    number_of_payment_installments INTEGER,
    send_email_reminder BOOLEAN,
    category_id INTEGER,
    FOREIGN KEY (category_id) references categories(id)
);

create table income_expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    expense_value DOUBLE,
    expense_date DATE,
    description VARCHAR(100),
    fixed_expense BOOLEAN,
    category_id INTEGER,
    FOREIGN KEY (category_id) references categories(id)
);